### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by Chanarin** [clovaai/mxfont#18]
Could you help with this error please? 

Traceback (most recent call last):
  File "C:\Users\user\Desktop\mxfont\train.py", line 185, in <module>
    main()
  File "C:\Users\user\Desktop\mxfont\train.py", line 181, in main
    train(args, cfg)
  File "C:\Users\user\Desktop\mxfont\train.py", line 167, in train
    trainer.train(trn_loader, st_step, cfg.max_iter)
  File "C:\Users\user\Desktop\mxfont\trainer\fact_trainer.py", line 145, in train
    self.add_ac_losses_and_update_stats(
  File "C:\Users\user\Desktop\mxfont\trainer\fact_trainer.py", line 281, in add_ac_losses_and_update_stats
    ac_loss_c, cross_ac_loss_c, acc_c = self.infer_comp_ac(char_facts, comp_ids)
  File "C:\Users\user\Desktop\mxfont\trainer\fact_trainer.py", line 251, in infer_comp_ac
    acc = T_probs[cids, eids].sum() / n_experts
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by SanghyukChun** [comment]
It seems that you are trying to run the implementation without GPU.
Our implementation does not afford CPU, therefore I close the issue.

**Comment by fanabcd** [comment]
没有提供单GPU的渠道吗
